version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wiki_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  etl:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data: